# Generated by Django 3.2.19 on 2024-03-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='AVAILABLESEATS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.availableseats'),
        ),
    ]
