# Generated by Django 3.2.19 on 2024-04-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_driverrequest_userrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverrequest',
            old_name='request',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='replay',
            new_name='status',
        ),
    ]
