# Generated by Django 3.2.19 on 2024-04-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240404_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverrequest',
            old_name='replay',
            new_name='request',
        ),
    ]
