# Generated by Django 3.2.19 on 2024-04-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_replay_driverrequest_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Feedback', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
